FROM amd64/ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive
ARG USER_ID=1000
ARG GROUP_ID=1000

# Proxy arguments
ARG http_proxy
ARG https_proxy
ARG ftp_proxy
ARG all_proxy
ARG no_proxy
ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG FTP_PROXY
ARG ALL_PROXY
ARG NO_PROXY

# =============================================================================
# Ubuntu 22.04 — Embedded Linux build environment (Buildroot, Yocto, OpenWrt)
# =============================================================================

RUN set -eux; \
    HP="${http_proxy:-${HTTP_PROXY:-}}"; \
    HPS="${https_proxy:-${HTTPS_PROXY:-${HP:-}}}"; \
    if [ -n "${HP}" ] || [ -n "${HPS}" ]; then \
        printf 'Acquire::http::Proxy "%s";\nAcquire::https::Proxy "%s";\n' "${HP}" "${HPS}" > /etc/apt/apt.conf.d/99proxy; \
    fi; \
    echo 'Acquire::ForceIPv4 "true";' > /etc/apt/apt.conf.d/99force-ipv4; \
    echo "dash dash/sh boolean false" | debconf-set-selections; \
    dpkg-reconfigure -f noninteractive dash

RUN set -eux; \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        apt-utils \
        autoconf \
        automake \
        bc \
        bison \
        build-essential \
        chrpath \
        corkscrew \
        cpio \
        curl \
        debianutils \
        debootstrap \
        device-tree-compiler \
        dfu-util \
        dialog \
        diffstat \
        dos2unix \
        dosfstools \
        doxygen \
        fdisk \
        file \
        flex \
        g++-multilib \
        gawk \
        gcc \
        gcc-multilib \
        gettext \
        git \
        git-lfs \
        help2man \
        iproute2 \
        iputils-ping \
        jq \
        libacl1 \
        libc6-dev-i386 \
        libegl1-mesa \
        libgnutls28-dev \
        liblz4-tool \
        libncurses5-dev \
        libnl-3-dev \
        libnl-route-3-dev \
        libsdl1.2-dev \
        libssl-dev \
        libxml-parser-perl \
        locales \
        lz4 \
        mesa-common-dev \
        nano \
        neovim \
        net-tools \
        pigz \
        pseudo \
        pylint \
        python3 \
        python3-dev \
        python3-distutils \
        python3-git \
        python3-jinja2 \
        python3-pexpect \
        python3-pip \
        python3-sphinx \
        python3-subunit \
        qemu-user-static \
        repo \
        rsync \
        socat \
        subversion \
        sudo \
        swig \
        texinfo \
        time \
        tmux \
        u-boot-tools \
        unzip \
        usbutils \
        vim \
        wget \
        xterm \
        xxd \
        xz-utils \
        zip \
        zlib1g-dev \
        zstd \
        sharutils \
        libusb-1.0-0-dev \
        libusb-dev \
        libreadline-dev \
        xz-utils \ 
        python2 \ 
        python2-dev \ 
        sharutils \ 
        zip \
    && rm -rf /var/lib/apt/lists/* \
    && rm -f /etc/apt/apt.conf.d/99proxy /etc/apt/apt.conf.d/99force-ipv4

RUN set -eux; \
    pip3 install --no-cache-dir \
        jsonschema \
        Mako \
        pyelftools \
        PyYAML \
        yamllint \
    && rm -rf /root/.cache/pip

RUN set -eux; \
    locale-gen en_US en_US.UTF-8

ENV LC_ALL="en_US.UTF-8" \
    LC_CTYPE="en_US.UTF-8" \
    LC_NUMERIC="en_US.UTF-8"

RUN groupadd -g ${GROUP_ID} builder \
    || groupmod -n builder $(getent group ${GROUP_ID} | cut -d: -f1) && \
    useradd -l -u ${USER_ID} -g ${GROUP_ID} -m -s /bin/bash builder && \
    echo "builder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER builder
WORKDIR /workspace

CMD ["/bin/bash"]
