# syntax=docker/dockerfile:1.4
FROM --platform=linux/amd64 ubuntu:18.04 AS base

ARG DEBIAN_FRONTEND=noninteractive

# Proxy arguments
ARG http_proxy
ARG https_proxy
ARG ftp_proxy
ARG all_proxy
ARG no_proxy
ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG FTP_PROXY
ARG ALL_PROXY
ARG NO_PROXY

RUN set -eux; \
    HP="${http_proxy:-${HTTP_PROXY:-}}"; \
    HPS="${https_proxy:-${HTTPS_PROXY:-${HP:-}}}"; \
    if [ -n "${HP}" ] || [ -n "${HPS}" ]; then \
        printf 'Acquire::http::Proxy "%s";\nAcquire::https::Proxy "%s";\n' "${HP}" "${HPS}" > /etc/apt/apt.conf.d/99proxy; \
    fi; \
    echo 'Acquire::ForceIPv4 "true";' > /etc/apt/apt.conf.d/99force-ipv4; \
    echo "dash dash/sh boolean false" | debconf-set-selections; \
    dpkg-reconfigure -f noninteractive dash

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt/lists,sharing=locked \
    set -eux; \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        bc \
        bison \
        build-essential \
        chrpath \
        cpio \
        curl \
        debianutils \
        device-tree-compiler \
        diffstat \
        file \
        flex \
        gawk \
        gcc-multilib \
        gettext \
        git \
        git-lfs \
        gosu \
        iproute2 \
        jq \
        libelf-dev \
        libncurses5-dev \
        libnl-3-dev \
        libnl-route-3-dev \
        libssl-dev \
        libxml-parser-perl \
        locales \
        pigz \
        python \
        python3 \
        python3-dev \
        python3-distutils \
        python3-pip \
        python3-setuptools \
        rsync \
        socat \
        sudo \
        swig \
        texinfo \
        time \
        u-boot-tools \
        unzip \
        uuid-dev \
        wget \
        xxd \
        xz-utils \
        zip \
        zlib1g-dev \
        zstd \
    && rm -f /etc/apt/apt.conf.d/99proxy /etc/apt/apt.conf.d/99force-ipv4

RUN set -eux; \
    pip3 install --no-cache-dir \
        jsonschema \
        Mako \
        pyelftools \
        PyYAML \
    && rm -rf /root/.cache/pip

RUN set -eux; \
    locale-gen en_US.UTF-8

ENV LC_ALL="en_US.UTF-8" \
    LANG="en_US.UTF-8" \
    LC_CTYPE="en_US.UTF-8" \
    LC_NUMERIC="en_US.UTF-8"

COPY docker/entrypoint.sh /usr/local/bin/entrypoint.sh

WORKDIR /workspace
ENTRYPOINT ["entrypoint.sh"]
CMD ["bash"]
